import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'employees',
        path: '',
        title: 'Employees',
        translateKey: 'nav.employees.employees',
        icon: 'employees',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'employees.list',
                path: '/employees',
                title: 'Employees',
                translateKey: 'nav.employees.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'employees.import',
                path: '/employees/import',
                title: 'Import Employees',
                translateKey: 'nav.employees.import',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'employees.import-history',
                path: '/employees/import-history',
                title: 'Import History',
                translateKey: 'nav.employees.import-history',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            {
                key: 'employees.generate-document',
                path: '/employees/generate-document',
                title: 'Generate Document',
                translateKey: 'nav.employees.generate-document',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'employees.update-request',
                path: '/employees/update-request',
                title: 'Update Request',
                translateKey: 'nav.employees.update-request',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'organization',
        path: '',
        title: 'Organization',
        translateKey: 'nav.organization.organization',
        icon: 'employees',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'organization.clientgroup',
                path: '/organization/client-groups',
                title: 'Client Groups',
                translateKey: 'nav.organization.clientgroup',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'organization.company',
                path: '/organization/companies',
                title: 'Companies',
                translateKey: 'nav.organization.company',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'organization.location',
                path: '/organization/locations',
                title: 'Locations',
                translateKey: 'nav.organization.location',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'organization.sub-location',
                path: '/organization/sub-locations',
                title: 'Sub Locations',
                translateKey: 'nav.organization.sub-location',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'organization.announcement',
                path: '/organization/announcements',
                title: 'Announcement',
                translateKey: 'nav.organization.announcement',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'organization.policy',
                path: '/organization/policies',
                title: 'Company Policy',
                translateKey: 'nav.organization.policy',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'rolesandpermission',
        path: '',
        title: 'Roles and Permissions',
        translateKey: 'nav.rolesandpermission.rolesandpermission',
        icon: 'security',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'rolesandpermission.users',
                path: '/users',
                title: 'Users',
                translateKey: 'nav.rolesandpermission.users',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'rolesandpermission.roles',
                path: '/roles',
                title: 'Roles',
                translateKey: 'nav.rolesandpermission.roles',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'rolesandpermission.permissions',
                path: '/permissions',
                title: 'Permissions',
                translateKey: 'nav.rolesandpermission.permissions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
